package template

import (
	"fmt"
	"strings"
	"time"

	"github.com/supermodeltools/uncompact/internal/casedata"
)

// RenderCaseBomb produces a token-budgeted Markdown case context bomb.
// Sections are dropped from the bottom up when the budget is exceeded.
func RenderCaseBomb(t *casedata.CaseTimeline, maxTokens int) (string, int) {
	// Build sections in priority order (highest first)
	sections := []struct {
		name   string
		render func() string
	}{
		{"overview", func() string { return renderOverview(t) }},
		{"deadlines", func() string { return renderDeadlines(t) }},
		{"workflow", func() string { return renderWorkflow(t) }},
		{"followups", func() string { return renderFollowups(t) }},
		{"timeline", func() string { return renderTimeline(t) }},
		{"eservice", func() string { return renderEService(t) }},
	}

	// Render all sections
	rendered := make([]string, len(sections))
	for i, s := range sections {
		rendered[i] = s.render()
	}

	// Build header
	header := fmt.Sprintf("# Case Context — %s (#%s)", t.Case.CaseName, t.Case.FileNumber)

	// Assemble from highest to lowest priority, dropping from bottom when over budget
	for drop := len(rendered); drop >= 0; drop-- {
		parts := []string{header}
		for i := 0; i < drop; i++ {
			if rendered[i] != "" {
				parts = append(parts, rendered[i])
			}
		}
		parts = append(parts, fmt.Sprintf("\n> Case context generated by Uncompact at %s",
			time.Now().UTC().Format(time.RFC3339)))

		full := strings.Join(parts, "\n\n")
		tokens := CountTokens(full)
		if tokens <= maxTokens || drop == 0 {
			return full, tokens
		}
	}

	// Should never reach here, but just in case
	result := header + fmt.Sprintf("\n\n> Case context generated by Uncompact at %s",
		time.Now().UTC().Format(time.RFC3339))
	return result, CountTokens(result)
}

func renderOverview(t *casedata.CaseTimeline) string {
	c := t.Case
	var lines []string
	lines = append(lines, "## Overview")
	lines = append(lines, fmt.Sprintf("- **Case**: %s", c.CaseName))
	if c.CaseNumber != "" {
		lines = append(lines, fmt.Sprintf("- **Case Number**: %s", c.CaseNumber))
	}
	lines = append(lines, fmt.Sprintf("- **Status**: %s", c.Status))
	if c.ClientName != "" || c.OpposingParty != "" {
		lines = append(lines, fmt.Sprintf("- **Client**: %s | **Opposing**: %s", c.ClientName, c.OpposingParty))
	}
	if c.SOLDate != "" {
		lines = append(lines, fmt.Sprintf("- **SOL**: %s", c.SOLDate))
	}
	if c.DateOfLoss != "" {
		lines = append(lines, fmt.Sprintf("- **Date of Loss**: %s", c.DateOfLoss))
	}
	if c.LeadAttorney != "" {
		lines = append(lines, fmt.Sprintf("- **Lead**: %s", c.LeadAttorney))
	}
	if c.AssignedParalegal != "" {
		lines = append(lines, fmt.Sprintf("- **Paralegal**: %s", c.AssignedParalegal))
	}
	if c.Court != "" {
		lines = append(lines, fmt.Sprintf("- **Court**: %s", c.Court))
	}
	if c.Judge != "" {
		lines = append(lines, fmt.Sprintf("- **Judge**: %s", c.Judge))
	}
	if c.CaseType != "" {
		lines = append(lines, fmt.Sprintf("- **Type**: %s", c.CaseType))
	}
	return strings.Join(lines, "\n")
}

func renderDeadlines(t *casedata.CaseTimeline) string {
	if len(t.Deadlines) == 0 {
		return ""
	}
	var lines []string
	lines = append(lines, "## Active Deadlines")
	lines = append(lines, "| Due | Type | Description | Status |")
	lines = append(lines, "|-----|------|-------------|--------|")
	for _, d := range t.Deadlines {
		lines = append(lines, fmt.Sprintf("| %s | %s | %s | %s |",
			d.DueDate, d.Type, d.Description, d.Status))
	}
	return strings.Join(lines, "\n")
}

func renderWorkflow(t *casedata.CaseTimeline) string {
	if t.Workflow.CurrentStage == "" {
		return ""
	}
	var lines []string
	lines = append(lines, fmt.Sprintf("## Workflow: %s", t.Workflow.CurrentStage))
	for _, task := range t.Workflow.Tasks {
		check := "[ ]"
		if task.Status == "COMPLETED" {
			check = "[x]"
		}
		suffix := ""
		if task.Status == "IN_PROGRESS" || task.Status == "DISPATCHED" {
			suffix = fmt.Sprintf(" -- %s", task.Status)
		}
		if task.DueDate != "" {
			suffix += fmt.Sprintf(" (due %s)", task.DueDate)
		}
		lines = append(lines, fmt.Sprintf("- %s %s%s", check, task.Title, suffix))
	}
	return strings.Join(lines, "\n")
}

func renderFollowups(t *casedata.CaseTimeline) string {
	// Only show open follow-ups
	var open []casedata.FollowupEvent
	for _, f := range t.Followups {
		if f.Status == "waiting" || f.Status == "overdue" || f.Status == "escalated" {
			open = append(open, f)
		}
	}
	if len(open) == 0 {
		return ""
	}
	var lines []string
	lines = append(lines, "## Open Follow-ups")
	lines = append(lines, "| Sent | To | Subject | Expected | Status | Count |")
	lines = append(lines, "|------|----|---------|----------|--------|-------|")
	for _, f := range open {
		lines = append(lines, fmt.Sprintf("| %s | %s | %s | %s | %s | %d |",
			f.SentDate, f.SentTo, f.Subject, f.ExpectedResponseDate, f.Status, f.FollowUpCount))
	}
	return strings.Join(lines, "\n")
}

func renderTimeline(t *casedata.CaseTimeline) string {
	if len(t.AuditTrail) == 0 && len(t.Milestones) == 0 {
		return ""
	}

	var lines []string
	lines = append(lines, "## Timeline")

	if len(t.Milestones) > 0 {
		lines = append(lines, "### Milestones")
		lines = append(lines, "| Date | Name | Status | Assigned | Deliverable |")
		lines = append(lines, "|------|------|--------|----------|-------------|")
		for _, m := range t.Milestones {
			lines = append(lines, fmt.Sprintf("| %s | %s | %s | %s | %s |",
				m.ScheduledDate, m.Name, m.Status, m.AssignedTo, m.Deliverable))
		}
	}

	if len(t.AuditTrail) > 0 {
		lines = append(lines, "### Audit Trail")
		lines = append(lines, "| Time | Action | Transition | Details |")
		lines = append(lines, "|------|--------|------------|---------|")
		for _, a := range t.AuditTrail {
			transition := ""
			if a.FromState != "" || a.ToState != "" {
				transition = fmt.Sprintf("%s -> %s", a.FromState, a.ToState)
			}
			detail := a.Details
			if len(detail) > 80 {
				detail = detail[:80] + "..."
			}
			lines = append(lines, fmt.Sprintf("| %s | %s | %s | %s |",
				a.Timestamp, a.Action, transition, detail))
		}
	}

	return strings.Join(lines, "\n")
}

func renderEService(t *casedata.CaseTimeline) string {
	if len(t.EService) == 0 {
		return ""
	}
	var lines []string
	lines = append(lines, "## eService Documents")
	lines = append(lines, "| Received | Type | File | Status |")
	lines = append(lines, "|----------|------|------|--------|")
	for _, e := range t.EService {
		lines = append(lines, fmt.Sprintf("| %s | %s | %s | %s |",
			e.ReceivedAt, e.DocType, e.PDFFilename, e.StagingStatus))
	}
	return strings.Join(lines, "\n")
}
